feat(package): update pyjwt to 2.4.0
TencentBlueKing/bkpaas-python-sdk pull request #79
Opened 2022-07-07 09:07 UTC by nannan00

2022-07-12 02:41 UTC, piglei commented
LGTM

2022-07-12 03:33 UTC, shabbywu requested changes

2022-07-12 03:33 UTC, shabbywu commented on sdks/blue-krill/blue_krill/auth/jwt.py
> +        token = jwt.encode(payload, key=self.auth_conf.key, algorithm=self.auth_conf.algorithm)
作为一个公共库, 我不确定锁定 pyjwt 的版本到 `^2.4.0` 是不是一个好做法。一般情况下, 我认为公共库是要尽可能的不限制依赖库的版本号, 除非是明确遇到兼容性的问题。

> 例如 pyjwt 1.x 和 2.x 的 encode 接口返回类型发送变化, 这种情况下锁定 `<2.0.0` 就可以认为是合理的。

鉴于这次将 pyjwt 从 1.x 升级至 2.x 的改动并不大, 例如以下的代码就可以同时适配 `1.x` 和 `2.x` 的 pyjwt 代码.
我认为可以将 pyjwt 的版本指定为 "*", 具体的版本限制则由依赖的项目进行控制, **避免后续 pyjwt 修复安全漏洞后, 需要先升级各个工具库，才能升级项目中对应的依赖版本。**

```python
import six
token = six.ensure_str(jwt.encode(payload, key=self.auth_conf.key, algorithm=self.auth_conf.algorithm))
```

2022-07-13 01:34 UTC, shabbywu approved these changes
LGTM

2022-07-13 01:37 UTC, merged